/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#0c0e16",
        "on-primary-container": "#00156d",
        "surface-container-high": "#1d1f2a",
        "error": "#ff6e84",
        "surface-container-lowest": "#000000",
        "error-dim": "#d73357",
        "on-tertiary": "#4a0001",
        "primary-fixed-dim": "#8998f0",
        "error-container": "#a70138",
        "outline": "#74757f",
        "secondary-dim": "#ec8300",
        "tertiary-container": "#fd493b",
        "inverse-on-surface": "#53545e",
        "on-surface-variant": "#aaaab5",
        "on-background": "#e4e4f0",
        "on-error": "#490013",
        "on-secondary-fixed": "#522a00",
        "primary-fixed": "#96a5ff",
        "secondary": "#ff8f06",
        "surface-dim": "#0c0e16",
        "on-secondary": "#462300",
        "on-primary-fixed": "#00083f",
        "outline-variant": "#464751",
        "inverse-primary": "#4958ac",
        "primary": "#9aa8ff",
        "on-error-container": "#ffb2b9",
        "tertiary": "#ff7161",
        "on-tertiary-fixed": "#3a0001",
        "on-secondary-container": "#fff6f1",
        "surface": "#0c0e16",
        "tertiary-fixed-dim": "#ff7c6c",
        "surface-container-highest": "#222531",
        "surface-tint": "#9aa8ff",
        "on-primary": "#122479",
        "surface-variant": "#222531",
        "surface-bright": "#292c38",
        "on-surface": "#e4e4f0",
        "surface-container": "#171923",
        "on-secondary-fixed-variant": "#7b4200",
        "secondary-fixed-dim": "#ffb373",
        "on-tertiary-fixed-variant": "#7a0003",
        "tertiary-fixed": "#ff9385",
        "surface-container-low": "#11131c",
        "secondary-fixed": "#ffc699",
        "secondary-container": "#8f4e00",
        "primary-container": "#8c9bf3",
        "tertiary-dim": "#ff7161",
        "primary-dim": "#8998f0",
        "on-tertiary-container": "#110000",
        "on-primary-fixed-variant": "#1b2c7f",
        "inverse-surface": "#faf8ff"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
  plugins: [],
}
